# Generated by Django 5.0.2 on 2024-05-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='volume_max',
            field=models.IntegerField(),
        ),
    ]
