# Generated by Django 5.0.2 on 2024-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0003_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photos_passeport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
    ]
