# Generated by Django 5.0.2 on 2024-06-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0004_alter_utilisateur_photos_passeport'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
