# Generated by Django 5.0.2 on 2024-06-07 23:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0005_annonce_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='poids_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='volume_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='annoncepalier',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce_paliers', to='ouanis.annonce'),
        ),
        migrations.AlterField(
            model_name='annoncepalier',
            name='palier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palier_annonces', to='ouanis.palier'),
        ),
        migrations.AlterField(
            model_name='annoncetag',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce_tags', to='ouanis.annonce'),
        ),
        migrations.AlterField(
            model_name='annoncetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_annonces', to='ouanis.tag'),
        ),
        migrations.AlterField(
            model_name='demandeannonce',
            name='poids',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='demandeannonce',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annonce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeannonce',
            name='volume',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='demandedecomptevoyageur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_compte_voyageur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palier',
            name='from_poids',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='palier',
            name='prix',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='palier',
            name='to_poids',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")]),
        ),
    ]
