# Generated by Django 5.0.2 on 2024-06-11 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0006_alter_annonce_createur_alter_annonce_poids_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouanis.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
