# Generated by Django 5.0.2 on 2024-06-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0008_payment_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
