# Generated by Django 5.0.2 on 2024-06-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
