# Generated by Django 5.0.2 on 2024-06-14 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0010_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeannonce',
            name='prix_total',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
