# Generated by Django 5.0.2 on 2024-06-18 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0012_rename_to_poids_palier_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='total_money',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
